### ISSUE TITLE
下拉上拉都存在问题

### ISSUE THREAD

**Issue by hioyes** [wcy10586/ptrload#1]

**Comment by wcy10586** [comment]
存在什么问题？

**Comment by hioyes** [comment]
![default](https://cloud.githubusercontent.com/assets/6267747/19633511/2431d888-99e5-11e6-86f3-bba0170cf10a.png)
卡住了，使劲往下拉拉就出来了

**Comment by wcy10586** [comment]
问题已经解决了，是由于在不满屏情况下 下拉刷新和 上拉加载冲突了
